BlogProject/BlogProject.UI/Areas/Admin/Controllers/PostController.cs
using BlogProject.CORE.Service;
using BlogProject.MODEL.Entities;
using BlogProject.UI.Models.VM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace BlogProject.UI.Areas.Admin.Controllers
{
    [Area("Admin"), Authorize]
    public class PostController : Controller
    {
        private readonly ICoreService<Category> categoryService;
        private readonly ICoreService<Post> postService;
        private readonly ICoreService<User> userService;
        public PostController(ICoreService<Category> categoryService, ICoreService<Post> postService, ICoreService<User> userService)
        {
            this.categoryService = categoryService;
            this.postService = postService;
            this.userService = userService;
        }
        public IActionResult ListPost()
        {
            return View(postService.GetAll());
        }
        public IActionResult AddPost()
        {
            //Addpost view gösterecek
            ViewBag.Categories = categoryService.GetActive();
            ViewBag.Users = userService.GetActive();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddPost(IFormCollection gelenMakale)
        {
            Post eklenecekPost = new Post();
            eklenecekPost.Title = gelenMakale["title"];
            eklenecekPost.PostDetail = gelenMakale["detail"];
            eklenecekPost.Tags = gelenMakale["tags"];
            eklenecekPost.ImagePath = gelenMakale["imagePath"];
            eklenecekPost.ViewCount = Convert.ToInt32(gelenMakale["viewCount"]);
            eklenecekPost.CategoryID = Guid.Parse(gelenMakale["categoryId"]);
            eklenecekPost.UserID = Guid.Parse(gelenMakale["userId"]);
            if (ModelState.IsValid)
            {

                return RedirectToAction(nameof(ListPost));
            }
            return View(gelenMakale);
        }

        public IActionResult ActivatePost(Guid id)
        {
            postService.Activate(id);
            return RedirectToAction("ListPost");
        }
    }
}

BlogProject/BlogProject.UI/Controllers/CategoryController.cs
using BlogProject.CORE.Service;
using BlogProject.MODEL.Entities;
using BlogProject.UI.Models.VM;
using Microsoft.AspNetCore.Mvc;
using System;

namespace BlogProject.UI.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICoreService<Category> categoryService;
        private readonly ICoreService<Post> postService;
        private readonly ICoreService<User> userService;

        public CategoryController(ICoreService<Category> categoryService, ICoreService<Post> postService, ICoreService<User> userService)
        {
            this.categoryService = categoryService;
            this.postService = postService;
            this.userService = userService;
        }

        public IActionResult Index()
        {
            return View(categoryService.GetActive());
        }

    }
}

BlogProject/BlogProject.UI/Controllers/PostController.cs
using BlogProject.CORE.Service;
using BlogProject.MODEL.Entities;
using BlogProject.UI.Models.VM;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace BlogProject.UI.Controllers
{
    public class PostController : Controller
    {
        private readonly ICoreService<Category> categoryService;
        private readonly ICoreService<Post> postService;
        private readonly ICoreService<User> userService;

        public PostController(ICoreService<Category> categoryService, ICoreService<Post> postService, ICoreService<User> userService)
        {
            this.categoryService = categoryService;
            this.postService = postService;
            this.userService = userService;
        }

        public IActionResult PostByID(Guid id)
        {
            SinglePostVM singlePostVM = new SinglePostVM();
            singlePostVM.Post = postService.GetByID(id);
            singlePostVM.User = userService.GetByDefault(x => x.ID == postService.GetByID(id).UserID);
            ViewBag.Categories = categoryService.GetActive();
            ViewBag.RandomPosts = postService.GetActive().Where(x=>x.CategoryID==postService.GetByID(id).CategoryID).Take(3).ToList();
            return View(singlePostVM);
        }

        public IActionResult PostByAuthor(Guid id)
        {
            ViewBag.Author = userService.GetByID(id).FirstName + " " + userService.GetByID(id).LastName;
            return View(postService.GetDefault(x=>x.UserID==id));
        }
        
        public IActionResult PostByCategory(Guid id)
        {
            PostUserVM postUserVM = new PostUserVM();
            postUserVM.Posts = postService.GetDefault(x => x.CategoryID == id);
            postUserVM.Users = userService.GetAll();
            return View(postUserVM);
        }

        [HttpPost]
        public IActionResult PostBySearch(string query)
        {
            PostUserVM postUserVM = new PostUserVM();
            postUserVM.Posts = postService.GetDefault(x => x.Title.Contains(query));
            postUserVM.Users = userService.GetAll();
            return View(postUserVM);
        }
    }
}

BlogProject/BlogProject.UI/Views/Post/PostByAuthor.cshtml
@model IEnumerable<BlogProject.MODEL.Entities.Post>

@{
    ViewData["Title"] = ViewBag.Author;
}

@foreach (Post item in Model)
{
    <article class="col-12 col-md-6 tm-post">
        <hr class="tm-hr-primary">
        <a asp-controller="Post" asp-action="PostByID" asp-route-id="@item.ID" class="effect-lily tm-post-link tm-pt-60">
            <div class="tm-post-link-inner">
                <img src="~/@item.ImagePath" alt="Image" class="img-fluid">
            </div>
            <span class="position-absolute tm-new-badge">New</span>
            <h2 class="tm-pt-30 tm-color-primary tm-post-title">@item.Title</h2>
        </a>
        <p class="tm-pt-30">
            @if(item.PostDetail.Length>100)
            {
                item.PostDetail.Substring(0, 100).ToString();<label>...</label>
            }
            else
            {
                item.PostDetail.ToString();
            }

        </p>
        <div class="d-flex justify-content-between tm-pt-45">
            <span class="tm-color-primary">@item.Tags</span>
            <span class="tm-color-primary">@item.CreatedDate.Value.ToShortDateString()</span>
        </div>
        <hr>
        <div class="d-flex justify-content-between">
            <span><i class="fa fa-eye"></i>  @item.ViewCount.ToString()</span>
            <span><i class="fa fa-user"></i> @ViewBag.Author </span>
        </div>
    </article>

}




<div class="row tm-row tm-mt-100 tm-mb-75">
    <div class="tm-prev-next-wrapper">
        <a href="#" class="mb-2 tm-btn tm-btn-primary tm-prev-next disabled tm-mr-20">Prev</a>
        <a href="#" class="mb-2 tm-btn tm-btn-primary tm-prev-next">Next</a>
    </div>
    <div class="tm-paging-wrapper">
        <span class="d-inline-block mr-3">Page</span>
        <nav class="tm-paging-nav d-inline-block">
            <ul>
                <li class="tm-paging-item active">
                    <a href="#" class="mb-2 tm-btn tm-paging-link">1</a>
                </li>
                <li class="tm-paging-item">
                    <a href="#" class="mb-2 tm-btn tm-paging-link">2</a>
                </li>
                <li class="tm-paging-item">
                    <a href="#" class="mb-2 tm-btn tm-paging-link">3</a>
                </li>
                <li class="tm-paging-item">
                    <a href="#" class="mb-2 tm-btn tm-paging-link">4</a>
                </li>
            </ul>
        </nav>
    </div>
</div>

BlogProject/BlogProject.UI/Views/Post/PostByCategory.cshtml
@model PostUserVM
@{
    ViewData["Title"] = "PostByCategory";
}

@foreach (Post item in Model.Posts)
{
    <article class="col-12 col-md-6 tm-post">
        <hr class="tm-hr-primary">
        <a asp-controller="Post" asp-action="PostByID" asp-route-id="@item.ID" class="effect-lily tm-post-link tm-pt-60">
            <div class="tm-post-link-inner">
                <img src="~/@item.ImagePath" alt="Image" class="img-fluid">
            </div>
            <span class="position-absolute tm-new-badge">New</span>
            <h2 class="tm-pt-30 tm-color-primary tm-post-title">@item.Title</h2>
        </a>
        <p class="tm-pt-30">
            @if (item.PostDetail.Length > 100)
            {
                item.PostDetail.Substring(0, 100).ToString();
                <label>...</label>
            }
            else
            {
                item.PostDetail.ToString();
            }

        </p>
        <div class="d-flex justify-content-between tm-pt-45">
            <span class="tm-color-primary">@item.Tags</span>
            <span class="tm-color-primary">@item.CreatedDate.Value.ToShortDateString()</span>
        </div>
        <hr>
        <div class="d-flex justify-content-between">
            <span><i class="fa fa-eye"></i>  @item.ViewCount.ToString()</span>
            <span>
                <i class="fa fa-user"></i> <a asp-action="PostByAuthor" asp-controller="Post" asp-route-id="@item.ID">
                    @Model.Users.Where(x=>x.ID==item.UserID).FirstOrDefault().FirstName @Model.Users.Where(x=>x.ID==item.UserID).FirstOrDefault().LastName
                </a>
            </span>
        </div>
    </article>

}




<div class="row tm-row tm-mt-100 tm-mb-75">
    <div class="tm-prev-next-wrapper">
        <a href="#" class="mb-2 tm-btn tm-btn-primary tm-prev-next disabled tm-mr-20">Prev</a>
        <a href="#" class="mb-2 tm-btn tm-btn-primary tm-prev-next">Next</a>
    </div>
    <div class="tm-paging-wrapper">
        <span class="d-inline-block mr-3">Page</span>
        <nav class="tm-paging-nav d-inline-block">
            <ul>
                <li class="tm-paging-item active">
                    <a href="#" class="mb-2 tm-btn tm-paging-link">1</a>
                </li>
                <li class="tm-paging-item">
                    <a href="#" class="mb-2 tm-btn tm-paging-link">2</a>
                </li>
                <li class="tm-paging-item">
                    <a href="#" class="mb-2 tm-btn tm-paging-link">3</a>
                </li>
                <li class="tm-paging-item">
                    <a href="#" class="mb-2 tm-btn tm-paging-link">4</a>
                </li>
            </ul>
        </nav>
    </div>
</div>

BlogProject/BlogProject.UI/Views/Post/PostByID.cshtml
@model SinglePostVM

@{
    ViewData["Title"] = Model.Post.Title;
}


<div class="row tm-row">
    <div class="col-12">
        <hr class="tm-hr-primary tm-mb-55">
        <!-- Video player 1422x800 -->
        <img src="~/@Model.Post.ImagePath" width="954" height="535" controls class="tm-mb-40" />

    </div>
</div>



<div class="row tm-row">
    <div class="col-lg-8 tm-post-col">
        <div class="tm-post-full">
            <div class="mb-4">
                <h2 class="pt-2 tm-color-primary tm-post-title">@Model.Post.Title</h2>
                <p class="tm-mb-40">
                    <a asp-action="PostByAuthor" asp-controller="Post" asp-route-id="@Model.User.ID"> @Model.User.FirstName  @Model.User.LastName</a> tarafından
                    <b> @Model.Post.CreatedDate.Value.ToShortDateString()</b> tarihinde paylaşıldı
                </p>
                <p>
                    @Model.Post.PostDetail.ToString()
                </p>

                <span class="d-block text-right tm-color-primary">@Model.Post.Tags</span>
            </div>

            <!-- Comments -->
            <div>
                <h2 class="tm-color-primary tm-post-title">Comments</h2>
                <hr class="tm-hr-primary tm-mb-45">
                <div class="tm-comment tm-mb-45">
                    <figure class="tm-comment-figure">
                        <img src="img/comment-1.jpg" alt="Image" class="mb-2 rounded-circle img-thumbnail">
                        <figcaption class="tm-color-primary text-center">Mark Sonny</figcaption>
                    </figure>
                    <div>
                        <p>
                            Praesent aliquam ex vel lectus ornare tritique. Nunc et eros
                            quis enim feugiat tincidunt et vitae dui. Nullam consectetur
                            justo ac ex laoreet rhoncus. Nunc id leo pretium, faucibus
                            sapien vel, euismod turpis.
                        </p>
                        <div class="d-flex justify-content-between">
                            <a href="#" class="tm-color-primary">REPLY</a>
                            <span class="tm-color-primary">June 14, 2020</span>
                        </div>
                    </div>
                </div>
                <div class="tm-comment-reply tm-mb-45">
                    <hr>
                    <div class="tm-comment">
                        <figure class="tm-comment-figure">
                            <img src="img/comment-2.jpg" alt="Image" class="mb-2 rounded-circle img-thumbnail">
                            <figcaption class="tm-color-primary text-center">Jewel Soft</figcaption>
                        </figure>
                        <p>
                            Nunc et eros quis enim feugiat tincidunt et vitae dui.
                            Nullam consectetur justo ac ex laoreet rhoncus. Nunc
                            id leo pretium, faucibus sapien vel, euismod turpis.
                        </p>
                    </div>
                    <span class="d-block text-right tm-color-primary">June 21, 2020</span>
                </div>
                <form action="" class="mb-5 tm-comment-form">
                    <h2 class="tm-color-primary tm-post-title mb-4">Your comment</h2>
                    <div class="mb-4">
                        <input class="form-control" name="name" type="text">
                    </div>
                    <div class="mb-4">
                        <input class="form-control" name="email" type="text">
                    </div>
                    <div class="mb-4">
                        <textarea class="form-control" name="message" rows="6"></textarea>
                    </div>
                    <div class="text-right">
                        <button class="tm-btn tm-btn-primary tm-btn-small">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <aside class="col-lg-4 tm-aside-col">
        <div class="tm-post-sidebar">
            <hr class="mb-3 tm-hr-primary">
            <h2 class="mb-4 tm-post-title tm-color-primary">Kategoriler</h2>
            @foreach (Category item in ViewBag.Categories)
            {
                <ul class="tm-mb-75 pl-5 tm-category-list">

                    <li><a asp-action="PostByCategory" asp-controller="Category" asp-route-id="@item.ID" class="tm-color-primary">@item.CategoryName</a></li>

                </ul>
            }

            <hr class="mb-3 tm-hr-primary">
            <h2 class="tm-mb-40 tm-post-title tm-color-primary">Benzer Makaleler</h2>

            @foreach (Post item in ViewBag.RandomPosts)
            {
                <a asp-action="PostByID" asp-controller="Post" asp-route-id="@item.ID" class="d-block tm-mb-40">
                    <figure>
                        <img src="@item.ImagePath" alt="Image" class="mb-3 img-fluid">
                        <figcaption class="tm-color-primary">@item.Title</figcaption>
                    </figure>
                </a>
            }


        </div>
    </aside>
</div>

BlogProject/BlogProject.UI/Views/Post/PostBySearch.cshtml
@{
    ViewData["Title"] = "PostBySearch";
}

<h1>PostBySearch</h1>